imports:
    - { resource: config.yml }
    - { resource: liip/imagine-dev.yml }

parameters:
    base_url_ru: bookary.dev
    base_url_en: bookary-en.dev
    message_queue_on: false

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
#        slackbot:
#            type: slack
#            token: '%slack_token%'
#            channel: '#dev'
#            level: critical
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    delivery_address: "%email_to%"
