imports:
    - { resource: config.yml }
    - { resource: liip/imagine.yml }

parameters:
    base_url: bookary.ru
    message_queue_on: true

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        slackbot:
            type: slack
            token: '%slack_token%'
            channel: '#prod'
            level: critical
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      nested
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: critical
        console:
            type:  console
