imports:
    - { resource: config.yml }
    - { resource: liip/imagine-dev.yml }

parameters:
    base_url_ru: bookary.dev
    base_url_en: bookary-en.dev

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        slackbot:
            type: slack
            token: 'xoxb-218905045585-dqQpUf6TqYRfVeOE6ss2FMjD'
            channel: '#dev'
            level: error
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
