imports:
    - { resource: config.yml }
    - { resource: liip/imagine.yml }

parameters:
    base_url_ru: bookary.ru
    base_url_en: bookary.eu

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        slackbot:
            type: slack
            token: 'xoxb-218905045585-dqQpUf6TqYRfVeOE6ss2FMjD'
            channel: '#prod'
            level: error
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      nested
        nested:
            type:  stream
            path: 'php://stderr'
            level: debug
        console:
            type:  console
