imports:
    - { resource: config.yml }
    - { resource: liip/imagine.yml }

parameters:
    base_url_ru: bookary.ru
    base_url_en: bookary.eu

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        slackbot:
            type: slack
            token: '%slack_token%'
            channel: '#prod'
            level: critical
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      nested
        nested:
            type:  stream
            path: 'php://stderr'
            level: critical
        console:
            type:  console

uecode_qpush:
    providers:
        aws:
            driver: aws
            key:    "%amazon.key%"
            secret: "%amazon.secret%"
            region: "%amazon.region%"
    queues:
        books_index:
            provider: aws
            options:
                push_notifications: true
                subscribers:
                    - { endpoint: "%base_scheme%://%base_url_ru%", protocol: http }