services:
    aws_s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: "factory"
        arguments:
            -
                credentials:
                    key:    "%amazon.key%"
                    secret: "%amazon.secret%"
                region:  "%amazon.region%"
                version: "latest"
                scheme:  "http"

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        local_upload_adapter:
            local:
                directory: "%kernel.root_dir%/../../book-cover-images"
                create:    true
        s3_upload_adapter:
            aws_s3:
                service_id:  "aws_s3.client"
                bucket_name: "%amazon.bucket_name%"

    filesystems:
        local_upload_fs:
            adapter: local_upload_adapter
        s3_upload_fs:
            adapter: s3_upload_adapter