sonata_admin:
    title:      Admin
    title_logo: bundles/app/images/logo.jpg
    dashboard:
        groups:
            catalog:
                items:
                    - admin.author
                    - admin.book
                    - admin.genre
                    - admin.tag
                    - admin.sequence
